# Generated by Django 4.1.4 on 2022-12-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_documents_author_alter_documents_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
    ]
