# Generated by Django 4.1.4 on 2022-12-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_users_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
