# Generated by Django 4.1.4 on 2022-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_alter_documents_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='owner',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dueño'),
        ),
    ]
